apiVersion: v1
kind: Secret
metadata:
  name: ingress-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ index .Values "nginx-ingress" "controller" "defaultTLS" "cert" }}
  tls.key: {{ index .Values "nginx-ingress" "controller" "defaultTLS" "key" }}